import json
import os
import requests

assets_path = "assets/custom-icons"

if not os.path.exists(assets_path):
    os.makedirs(assets_path)

data = requests.get("https://api.2fa.directory/v3/totp.json").json()

totps = []

for site in data:
  site_name = site[0]
  domain = site[1]['domain']
  try:
    img = site[1]['img']
  except:
    img = None
  extension = img.split(".")[-1] if img else "svg"
  if os.path.exists(f"{assets_path}/{domain}.{extension}"):
    totps.append({'name': site_name, 'domain': domain, 'extension': extension})
    continue
  url = f"https://raw.githubusercontent.com/2factorauth/twofactorauth/master/img/{img[0] if img else domain[0]}/{img if img else domain+".svg"}"
  res = requests.get(url)
  if res.status_code >= 400:
    print(f"Failed to get {domain}: {url}")
    continue
  with open(f"{assets_path}/{domain}.{extension}", "wb") as f:
    f.write(res.content)
  totps.append({'name': site_name, 'domain': domain, 'extension': extension})
  print(f"Got {extension} for {domain}")
  
print(f"Total of {len(totps)} sites!")

with open('assets/totp.json', 'w', encoding='utf-8') as f:
  json.dump(totps, f, indent=4)

# Generate customIcons.ts
custom_icons_content = """
/*
 * This file is automatically generated by scripts/scrape_totp.py.
 * Do not modify it directly.
 */

export const customIcons: { [key: string]: any } = {
"""

for icon_data in totps:
    filename = f"{icon_data['domain']}.{icon_data['extension']}"
    custom_icons_content += f"  '{filename}': require('../assets/custom-icons/{filename}'),\n"

custom_icons_content += "}; \n"

with open('utils/customIcons.ts', 'w', encoding='utf-8') as f:
    f.write(custom_icons_content)

print("Generated utils/customIcons.ts")